project_id = "eiwvgbksjmceafnozldm"

[functions.process-form]
verify_jwt = true

[functions.ai-process-form]
verify_jwt = true

[functions.create-razorpay-order]
verify_jwt = true

[functions.verify-razorpay-payment]
verify_jwt = true

[functions.customer-support-chat]
verify_jwt = false

[functions.form-assistant]
verify_jwt = true
