project_id = "eiwvgbksjmceafnozldm"

[functions.process-form]
verify_jwt = true

[functions.ai-process-form]
verify_jwt = true

[functions.create-razorpay-order]
verify_jwt = true

[functions.verify-razorpay-payment]
verify_jwt = true

[functions.stripe-create-payment]
verify_jwt = true

[functions.paypal-create-payment]
verify_jwt = true

[functions.razorpay-create-payment]
verify_jwt = true

[functions.razorpay-verify-payment]
verify_jwt = true

[functions.razorpay-create-subscription]
verify_jwt = true

[functions.customer-support-chat]
verify_jwt = true

[functions.form-assistant]
verify_jwt = true

[functions.auto-fill-form]
verify_jwt = true
