-- Update api_keys table schema to support hashed keys
-- Add key_prefix column to store first 12 characters for display
ALTER TABLE api_keys 
ADD COLUMN IF NOT EXISTS key_prefix text;

-- Add comment explaining the security model
COMMENT ON COLUMN api_keys.api_key IS 'SHA-256 hashed API key for secure storage. Keys are only shown once at creation.';
COMMENT ON COLUMN api_keys.key_prefix IS 'First 12 characters of the API key for display purposes (e.g., fsk_abc...)';

-- Add constraint to ensure hashed keys are the correct length (64 chars for SHA-256 hex)
ALTER TABLE api_keys 
ADD CONSTRAINT api_key_hash_length_check 
CHECK (length(api_key) = 64 OR length(api_key) > 64);

-- Note: Existing plaintext keys will need to be re-generated by users as they cannot be hashed retroactively